//! # Verity Agent OS — Runtime TLA+ Model Checker
//!
//! Continuously samples live transactions against the TLA+ specification
//! during production operation. Implements the **Ledger Rocket** pattern
//! (Jan 2026): deterministic execution with formal TLA+ verification of
//! capital-safety invariants.
//!
//! ## Architecture
//! - **tla-checker** v0.1.0: pure Rust TLA+ model checker (15K SLoC,
//!   WASM-compatible) for exploring all reachable states
//! - **modelator** v0.2.1: runs system under test against TLA+ traces
//!   generated by Apalache/TLC
//! - **State-space sampling**: continuously validates that production
//!   transactions conform to the verified state space
//!
//! ## Verified Invariants
//! - Conservation of Value: Σ entries = 0
//! - No double spends
//! - Capability token unforgeability
//! - Merkle root consistency
//!
//! Source: ARC42 v20.0 §3 VAOS Runtime TLA+ Model Checker, ADR-013

pub mod checker;
pub mod invariants;
pub mod coverage;
pub mod errors;

pub use checker::RuntimeTlaChecker;
pub use invariants::VerifiedInvariant;
pub use coverage::CoverageTracker;
pub use errors::TlaError;

use std::sync::Arc;
use tokio::sync::RwLock;

/// Central runtime TLA+ checking engine.
#[derive(Debug)]
pub struct RuntimeTlaEngine {
    checker: RuntimeTlaChecker,
    coverage: Arc<RwLock<CoverageTracker>>,
    config: TlaConfig,
}

#[derive(Debug, Clone)]
pub struct TlaConfig {
    /// Sampling rate — fraction of transactions to check (0.0–1.0)
    pub sampling_rate: f64,
    /// Whether to halt on invariant violation
    pub halt_on_violation: bool,
    /// Whether to emit OpenTelemetry spans for each check
    pub emit_telemetry: bool,
}

impl Default for TlaConfig {
    fn default() -> Self {
        Self {
            sampling_rate: 0.10,       // Check 10% of all transactions
            halt_on_violation: true,   // Safety-critical: halt on violation
            emit_telemetry: true,
        }
    }
}

impl RuntimeTlaEngine {
    pub fn new(config: TlaConfig) -> Self {
        Self {
            checker: RuntimeTlaChecker::new(),
            coverage: Arc::new(RwLock::new(CoverageTracker::new())),
            config,
        }
    }

    /// Sample a transaction against the TLA+ specification.
    ///
    /// Returns Ok(()) if the transaction conforms to all verified invariants,
    /// or a TlaError describing the violation.
    #[tracing::instrument(name = "runtime_tla.sample", level = "info", skip(self))]
    pub async fn sample_transaction(
        &self,
        transaction: &serde_json::Value,
    ) -> Result<(), TlaError> {
        // 1. Check sampling rate — use transaction hash for deterministic sampling
        let should_check = {
            let hash = blake3::hash(
                &serde_json::to_vec(transaction).unwrap_or_default()
            );
            let bucket = u64::from_le_bytes(hash.as_bytes()[..8].try_into().unwrap());
            (bucket as f64 / u64::MAX as f64) < self.config.sampling_rate
        };

        if !should_check {
            return Ok(());
        }

        // 2. Run TLA+ model checker on this transaction trace
        self.checker.check(transaction).await?;

        // 3. Update coverage metrics
        let mut cov = self.coverage.write().await;
        cov.record_check();

        Ok(())
    }

    /// Generate a coverage report showing what fraction of the
    /// verified state space has been observed in production.
    pub async fn coverage_report(&self) -> CoverageReport {
        self.coverage.read().await.report()
    }
}

#[derive(Debug, Clone)]
pub struct CoverageReport {
    pub total_checks: u64,
    pub invariants_verified: usize,
    pub state_space_explored_pct: f64,
    pub deviations_found: u64,
}
